Repository Slow-Heat-Index/BlockDasher, pull requests merged in 2021-11, with the labels that each got.

#29 Fix castle props.
  Assets/Resources/Models/Props/Castle/Bench/banco.png.meta
  Assets/Resources/Models/Props/Castle/Bench/banco1.png
  Assets/Resources/Models/Props/Castle/Bench/banco2.png
  Assets/Resources/Models/Props/Castle/Bench/bench.mtl
  Assets/Resources/Models/Props/Castle/Bench/bench.mtl.meta
  Assets/Resources/Models/Props/Castle/Bench/bench.obj
  Assets/Resources/Models/Props/Castle/Bench/bench.obj.meta
  Assets/Resources/Models/Props/Castle/Bench/benchPart1.mtl
  Assets/Resources/Models/Props/Castle/Bench/benchPart1.obj
  Assets/Resources/Models/Props/Castle/Bench/benchPart2.mtl
  Assets/Resources/Models/Props/Castle/Bench/benchPart2.obj
  Assets/Resources/Models/Props/Castle/CandlesTable/Materials.meta
  Assets/Resources/Models/Props/Castle/CandlesTable/Materials/candlesTable.mat
  Assets/Resources/Models/Props/Castle/CandlesTable/Materials/candlesTable.mat.meta
  Assets/Resources/Models/Props/Castle/CandlesTable/candleTablePart1.mtl
  Assets/Resources/Models/Props/Castle/CandlesTable/candleTablePart1.obj
  Assets/Resources/Models/Props/Castle/CandlesTable/candleTablePart2.mtl
  Assets/Resources/Models/Props/Castle/CandlesTable/candleTablePart2.obj
  Assets/Resources/Models/Props/Castle/CandlesTable/candlesTable.mtl
  Assets/Resources/Models/Props/Castle/CandlesTable/candlesTable.mtl.meta
  Assets/Resources/Models/Props/Castle/CandlesTable/candlesTable.obj
  Assets/Resources/Models/Props/Castle/CandlesTable/candlesTable.obj.meta
  Assets/Resources/Models/Props/Castle/CandlesTable/candlesTable.png.meta
  Assets/Resources/Models/Props/Castle/CandlesTable/candlesTable1.png
  Assets/Resources/Models/Props/Castle/CandlesTable/candlesTable2.png
Labels: enhancement, Art

#26 Add dead bush 2.
  Assets/Resources/Models/Props/Desert/deadBush2/deadBush2.mtl
  Assets/Resources/Models/Props/Desert/deadBush2/deadBush2.obj
  Assets/Resources/Models/Props/Desert/deadBush2/deadBush2.png
Labels: enhancement, Art

#31 Lava world
  Assets/Resources/Models/miniWorlds/LavaWorld/Old World/Materials.meta
  Assets/Resources/Models/miniWorlds/LavaWorld/Old World/Materials/miniLava-5-world-defaultMat.mat
  Assets/Resources/Models/miniWorlds/LavaWorld/Old World/Materials/miniLava-5-world-defaultMat.mat.meta
  Assets/Resources/Models/miniWorlds/LavaWorld/Old World/miniLava-5-world.obj
  Assets/Resources/Models/miniWorlds/LavaWorld/Old World/miniLava-5-world.obj.meta
  Assets/Resources/Models/miniWorlds/LavaWorld/Old World/miniLava-5-world.png
  Assets/Resources/Models/miniWorlds/LavaWorld/Old World/miniLava-5-world.png.meta
  Assets/Resources/Models/miniWorlds/LavaWorld/miniLava-5-world.obj
  Assets/Resources/Models/miniWorlds/LavaWorld/miniLava-5-world.png
Labels: enhancement, Art

#41 Added lvl 1 for desert
  Assets/Resources/Levels/lvl1Zone2.bytes
  Assets/Resources/Levels/lvl1Zone2.bytes.meta
Labels: enhancement, Level design

#42 Added lvl 2 for desert
  Assets/Resources/Levels/lvl2Zone2.bytes
  Assets/Resources/Levels/lvl2Zone2.bytes.meta
Labels: enhancement, Level design

#40 Dessert grass texture fixed #39
  Assets/Resources/Models/Blocks/TallGrassDesert/Default.png.meta
Labels: bug, Art

#43 Remove dash limit. Add gold, silver and bronze rankings.
  Assets/Resources/Levels/TestLevel.bytes
  Assets/Scenes/Editor.unity
  Assets/Scenes/Level.unity
  Assets/Scripts/Controller/GameEditor/MovementsTextField.cs
  Assets/Scripts/Controller/GameEditor/MovementsTextField.cs.meta
  Assets/Scripts/Controller/GameEditor/RankingTextField.cs
  Assets/Scripts/Controller/GameEditor/RankingTextField.cs.meta
  Assets/Scripts/Level/Player/Data/PlayerData.cs
  Assets/Scripts/Level/UI/MovementsLeftTextBehaviour.cs
  Assets/Scripts/Level/UI/MovementsLeftTextBehaviour.cs.meta
  Assets/Sources/Level/World.cs
Labels: enhancement, Game dev

#45 Add skybox support. Remove bronze rank.
  Assets/Resources/SkyBoxes/Garden.meta
  Assets/Resources/SkyBoxes/Garden/Skybox.mat
  Assets/Resources/SkyBoxes/Garden/Skybox.mat.meta
  Assets/Resources/SkyBoxes/Garden/nx.png
  Assets/Resources/SkyBoxes/Garden/nx.png.meta
  Assets/Resources/SkyBoxes/Garden/ny.png
  Assets/Resources/SkyBoxes/Garden/ny.png.meta
  Assets/Resources/SkyBoxes/Garden/nz.png
  Assets/Resources/SkyBoxes/Garden/nz.png.meta
  Assets/Resources/SkyBoxes/Garden/px.png
  Assets/Resources/SkyBoxes/Garden/px.png.meta
  Assets/Resources/SkyBoxes/Garden/py.png
  Assets/Resources/SkyBoxes/Garden/py.png.meta
  Assets/Resources/SkyBoxes/Garden/pz.png
  Assets/Resources/SkyBoxes/Garden/pz.png.meta
  Assets/Scenes/Editor.unity
  Assets/Scripts/Controller/GameEditor/RankingTextField.cs
  Assets/Scripts/Controller/GameEditor/SkyboxComboBox.cs
  Assets/Scripts/Controller/GameEditor/SkyboxComboBox.cs.meta
  Assets/Sources/Identification/Identifiers.cs
  Assets/Sources/Level/Manager/SkyboxManager.cs
  Assets/Sources/Level/Manager/SkyboxManager.cs.meta
  Assets/Sources/Level/Skyboxes.meta
  Assets/Sources/Level/Skyboxes/SkyboxWrapper.cs
  Assets/Sources/Level/Skyboxes/SkyboxWrapper.cs.meta
  Assets/Sources/Level/World.cs
  Assets/Sources/Registration/Registry.cs
Labels: enhancement, Game dev

#44 Added medal threshold
  Assets/Resources/Levels/IntroductoryLevel.bytes
  Assets/Resources/Levels/lvl1Zone2.bytes
  Assets/Resources/Levels/lvl2.bytes
  Assets/Resources/Levels/lvl2Zone2.bytes
  Assets/Resources/Levels/lvl3.bytes
  Assets/Resources/Levels/lvl3Zone2.bytes
  Assets/Resources/Levels/lvl4Zone2.bytes
  Assets/Resources/Levels/newlvl4.bytes
Labels: enhancement, Level design

#46 Wet block made darker
  Assets/Resources/Models/Blocks/WetSand/Black.png
  Assets/Resources/Models/Blocks/WetSand/White.png
Labels: Art

#49 Corner Bush
  Assets/Resources/Models/Props/Garden/LabyrinthCornerBush/SetoLaberintoEsquina.png
  Assets/Resources/Models/Props/Garden/LabyrinthCornerBush/labyrinthCornerBush.mtl
  Assets/Resources/Models/Props/Garden/LabyrinthCornerBush/labyrinthCornerBush.obj
Labels: enhancement, Art

#50 Art models
  Assets/Resources/Models/Player/new model/animations/character iddle 1.fbx
  Assets/Resources/Models/Player/new model/animations/character iddle 2.fbx
  Assets/Resources/Models/Player/new model/animations/character jump.fbx
  Assets/Resources/Models/Player/new model/animations/character snap back.fbx
  Assets/Resources/Models/Player/new model/character model.fbx
Labels: enhancement, Art

#56 Lvl5 zone1
  Assets/Resources/Levels/lvl5.bytes
Labels: Level design

#55 Add Post Processing Volume
  Assets/Resources/Models/Player/new model.meta
  Assets/Resources/Models/Player/new model/animations.meta
  Assets/Resources/Models/Player/new model/animations/character iddle 1.fbx.meta
  Assets/Resources/Models/Player/new model/animations/character iddle 2.fbx.meta
  Assets/Resources/Models/Player/new model/animations/character jump.fbx.meta
  Assets/Resources/Models/Player/new model/animations/character snap back.fbx.meta
  Assets/Resources/Models/Player/new model/character model.fbx.meta
  Assets/Resources/Models/Props.meta
  Assets/Resources/Models/Props/Garden.meta
  Assets/Resources/Models/Props/Garden/LabyrinthCornerBush.meta
  Assets/Resources/Models/Props/Garden/LabyrinthCornerBush/SetoLaberintoEsquina.png.meta
  Assets/Resources/Models/Props/Garden/LabyrinthCornerBush/labyrinthCornerBush.mtl.meta
  Assets/Resources/Models/Props/Garden/LabyrinthCornerBush/labyrinthCornerBush.obj.meta
  Assets/Resources/Social Media/SlowHeatIndexWeb.png.meta
  Assets/Scenes/Level.unity
  Assets/Scenes/Level/Global Volume Profile.asset
  Assets/Scenes/Level/Global Volume Profile.asset.meta
  Assets/Scenes/Level_Profiles.meta
  Assets/Scenes/Level_Profiles/Camera Profile.asset
  Assets/Scenes/Level_Profiles/Camera Profile.asset.meta
  Packages/manifest.json
  Packages/packages-lock.json
  ProjectSettings/ProjectSettings.asset
Labels: enhancement, Game dev

#57 Enemy and animations added
  Assets/Resources/Models/Enemies/killer/killer enemy attack.fbx
  Assets/Resources/Models/Enemies/killer/killer enemy attacks to resting position.fbx
  Assets/Resources/Models/Enemies/killer/killer enemy model.fbx
  Assets/Resources/Models/Player/new model/animations/character bump.fbx
  Assets/Resources/Models/Player/new model/animations/character death.fbx
  Assets/Resources/Models/Player/new model/animations/character fall.fbx
  Assets/Resources/Models/Player/new model/animations/character hello.fbx
Labels: enhancement, Art

#59 Changed tittle texture
  Assets/Images and buttons.meta
  Assets/Images and buttons/block-dasher.png
  Assets/Images and buttons/block-dasher.png.meta
  Assets/PlaceHolders/Title.png
Labels: Art

#60 Add shark entity. Fix restart buttons.
  Assets/Prefabs/Enemies/Shark.prefab
  Assets/Prefabs/Enemies/Shark.prefab.meta
  Assets/Prefabs/Enemies/SharkDisplay.prefab
  Assets/Prefabs/Enemies/SharkDisplay.prefab.meta
  Assets/Scenes/Editor.unity
  Assets/Scenes/Level.unity
  Assets/Scripts/EditorData.cs
  Assets/Scripts/Level/Entities/AggressiveEntity.cs
  Assets/Scripts/Level/Entities/RandomPathAwareEntity.cs
  Assets/Scripts/Level/Entities/SharkEntity.cs
  Assets/Scripts/Level/Entities/SharkEntity.cs.meta
  Assets/Scripts/Level/Generator/LevelGenerator.cs
  Assets/Scripts/Level/Player/Data/PlayerData.cs
  Assets/Scripts/UI/Game/GameplayUI.cs
  Assets/Scripts/UI/Game/LevelCompletedScreen.cs
  Assets/Sources/Identification/Identifiers.cs
  Assets/Sources/Level/Blocks/SpawnerBlock.cs
  Assets/Sources/Level/Chunk.cs
  Assets/Sources/Level/Manager/EntityManager.cs
  Assets/Sources/Level/MetadataSnapshot.cs
Labels: enhancement, Game dev

#61 Add UI SFX and Buttons Feedback
  Assets/Audio.meta
  Assets/Audio/Music.meta
  Assets/Audio/Music/castle.mp3
  Assets/Audio/Music/castle.mp3.meta
  Assets/Audio/Music/desert.mp3
  Assets/Audio/Music/desert.mp3.meta
  Assets/Audio/Music/gardens.mp3
  Assets/Audio/Music/gardens.mp3.meta
  Assets/Audio/SFX.meta
  Assets/Audio/SFX/LetsDash.mp3
  Assets/Audio/SFX/LetsDash.mp3.meta
  Assets/Audio/SFX/Return.mp3
  Assets/Audio/SFX/Return.mp3.meta
  Assets/Audio/SFX/buttonPressed.mp3
  Assets/Audio/SFX/buttonPressed.mp3.meta
  Assets/Audio/SFX/dash.mp3
  Assets/Audio/SFX/dash.mp3.meta
  Assets/Audio/SFX/enemyPunch.mp3
  Assets/Audio/SFX/enemyPunch.mp3.meta
  Assets/Audio/SFX/enemySpottedYou.mp3
  Assets/Audio/SFX/enemySpottedYou.mp3.meta
  Assets/Audio/SFX/falling.mp3
  Assets/Audio/SFX/falling.mp3.meta
  Assets/Audio/SFX/quickSandDash.mp3
  Assets/Audio/SFX/quickSandDash.mp3.meta
  Assets/Audio/SFX/sandDash.mp3
  Assets/Audio/SFX/sandDash.mp3.meta
  Assets/Audio/SFX/wallbump.mp3
  Assets/Audio/SFX/wallbump.mp3.meta
  Assets/Audio/SFX/waterDash.mp3
  Assets/Audio/SFX/waterDash.mp3.meta
  Assets/ButtonFeedBack.cs
  Assets/ButtonFeedBack.cs.meta
  Assets/Scenes/Level.unity
  Assets/Scenes/Level/Global Volume Profile.asset
  Assets/Scenes/Menu.unity
Labels: enhancement, Art

#62 Add Lvl1Zone3
  Assets/Prefabs/Player.prefab
  Assets/Resources/Levels/lvl1Zone3.bytes
  Assets/Resources/Levels/lvl1Zone3.bytes.meta
  Assets/Scripts/Level/Blocks/WaterBlockView.cs
  Assets/Scripts/Level/Player/Data/PlayerData.cs
Labels: Level design

#64 Shark model and idle animarion
  Assets/Resources/Models/Enemies/Shark/shark idle.fbx
  Assets/Resources/Models/Enemies/Shark/shark.fbx
Labels: enhancement, Art

#65 Improve level5
  Assets/Resources/Levels/lvl5.bytes
Labels: Level design

#70 Added lvl 2 at beach
  Assets/Resources/Levels/level_3_2.bytes
  Assets/Resources/Levels/level_3_2.bytes.meta
Labels: Level design

#72 Concept and sphere enemy added
  Assets/Resources/Concept/character idea concept.png
  Assets/Resources/Concept/enemies concept/killer enemy concept.png
  Assets/Resources/Concept/enemies concept/pusher enemy.png
  Assets/Resources/Concept/enemies concept/shark concept.png
  Assets/Resources/Concept/skin concept/candy colors.png
  Assets/Resources/Concept/skin concept/cubito de hielo.png
  Assets/Resources/Concept/skin concept/gelatina de mora.png
  Assets/Resources/Concept/skin concept/hell.png
  Assets/Resources/Concept/skin concept/lime.png
  Assets/Resources/Concept/skin concept/noir.png
  Assets/Resources/Models/Enemies/Sphere/pusher enemy model.fbx
Labels: enhancement, Art

#73 Art animation and concept
  Assets/Resources/Models/Enemies/Sphere/pusher enemy attack.fbx
  Assets/Resources/Models/Enemies/Sphere/pusher enemy idle.fbx
  Assets/Resources/Models/Enemies/Sphere/pusher enemy model.fbx
Labels: enhancement, Art

#74 Added castle desert
  Assets/Resources/Levels/level_2_5.bytes
  Assets/Resources/Levels/level_2_5.bytes.meta
Labels: Level design

#76 Added step count for new levels
  Assets/Resources/Levels/level_1_5.bytes
  Assets/Resources/Levels/level_3_1.bytes
  Assets/Resources/Levels/level_3_2.bytes
  Assets/Resources/Models/Enemies/Sphere/pusher enemy attack.fbx.meta
  Assets/Resources/Models/Enemies/Sphere/pusher enemy idle.fbx.meta
Labels: Level design

#78 Create personaje muerto.png
  Assets/Resources/Concept/personaje muerto.png
Labels: enhancement, Art

#81 Add All UI guides
  Assets/Resources/Interface/Guide/BuyCoins.png
  Assets/Resources/Interface/Guide/In-Game.png
  Assets/Resources/Interface/Guide/LevelLocked.png
  Assets/Resources/Interface/Guide/LevelSelector.png
  Assets/Resources/Interface/Guide/Lose(Continue).png
  Assets/Resources/Interface/Guide/Lose.png
  Assets/Resources/Interface/Guide/Menu.png
  Assets/Resources/Interface/Guide/Pause.png
  Assets/Resources/Interface/Guide/Store.png
  Assets/Resources/Interface/Guide/Win.png
  Assets/Resources/Interface/Guide/WorldLocked.png
Labels: Art

#83 Add sprite atlas
  Assets/Resources/Concept/personaje muerto.png.meta
  Assets/Resources/Interface/Atlas/Atlas.png
  Assets/Resources/Interface/Atlas/BuyCoins.png
  Assets/Resources/Interface/Atlas/InGame.png
  Assets/Resources/Interface/Atlas/LevelSelector.png
  Assets/Resources/Interface/Atlas/Menu.png
  Assets/Resources/Interface/Atlas/Pause-Lose-Win.png
  Assets/Resources/Interface/Atlas/Store.png
  Assets/Resources/Interface/Atlas/WorldSelector.png
  Assets/Resources/Interface/Guide/In-Game.png.meta
  Assets/Resources/Interface/Guide/LevelLocked.png.meta
  Assets/Resources/Interface/Guide/Lose(Continue).png.meta
  Assets/Resources/Interface/Guide/Lose.png.meta
  Assets/Resources/Interface/Guide/Menu.png.meta
  Assets/Resources/Interface/Guide/Pause.png.meta
  Assets/Resources/Interface/Guide/Store.png.meta
  Assets/Resources/Interface/Guide/Win.png.meta
  Assets/Resources/Interface/Guide/WorldLocked.png.meta
Labels: Art

#84 Update atlas
  Assets/Resources/Interface/Atlas/Atlas.png
  Assets/Resources/Interface/Atlas/WorldSelector.png
Labels: Art

#86 Create character drown.fbx
  Assets/Resources/Models/Player/animations/character drown.fbx
Labels: enhancement, Art

#88 Added level 3 world 3
  Assets/Resources/Levels/level_3_3.bytes
  Assets/Resources/Levels/level_3_3.bytes.meta
Labels: Level design

#91 Sounds implementation
  Assets/Audio/Music/beachTheme.mp3
  Assets/Audio/Music/beachTheme.mp3.meta
  Assets/Audio/Music/extraCoinsMusic.mp3
  Assets/Audio/Music/extraCoinsMusic.mp3.meta
  Assets/Audio/Music/loseMusic.mp3
  Assets/Audio/Music/loseMusic.mp3.meta
  Assets/Audio/Music/winMusic.mp3
  Assets/Audio/Music/winMusic.mp3.meta
  Assets/Audio/SFX/dash.mp3
  Assets/Audio/SFX/death.mp3
  Assets/Audio/SFX/death.mp3.meta
  Assets/Audio/SFX/falling.mp3
  Assets/Audio/SFX/quickSandDash.mp3
  Assets/Audio/SFX/wallbump.mp3
  Assets/DeathScreen.cs
  Assets/EnemySoundManager.cs
  Assets/EnemySoundManager.cs.meta
  Assets/MusicManager.cs
  Assets/MusicManager.cs.meta
  Assets/PlayerSoundManager.cs
  Assets/PlayerSoundManager.cs.meta
  Assets/Prefabs/Enemies/Sphere.prefab
  Assets/Prefabs/Enemies/Triangle.prefab
  Assets/Prefabs/Player.prefab
  Assets/Resources/Levels/level_1_5.bytes
  Assets/Scenes/Editor.unity
  Assets/Scenes/Level.unity
  Assets/Scripts/Level/Entities/AggressiveEntity.cs
  Assets/Scripts/Level/Entities/TriangleEntity.cs
  Assets/Scripts/Level/Player/Data/PlayerData.cs
  Assets/Scripts/UI/Game/LevelCompletedScreen.cs
Labels: Art, Game dev

#96 Add entity hint. Add sphere model.
  Assets/Prefabs/Enemies/Sphere.prefab
  Assets/Prefabs/Enemies/SphereDisplay.prefab
  Assets/Prefabs/Enemies/Triangle.prefab
  Assets/Prefabs/Enemies/TriangleDisplay.prefab
  Assets/Resources/Models/Enemies/Sphere/Dash.anim
  Assets/Resources/Models/Enemies/Sphere/Dash.anim.meta
  Assets/Resources/Models/Enemies/Sphere/Idle.anim
  Assets/Resources/Models/Enemies/Sphere/Idle.anim.meta
  Assets/Resources/Models/Enemies/Sphere/Model.fbx
  Assets/Resources/Models/Enemies/Sphere/Model.fbx.meta
  Assets/Resources/Models/Enemies/Sphere/SphereAnimator.controller
  Assets/Resources/Models/Enemies/Sphere/SphereAnimator.controller.meta
  Assets/Resources/Models/Enemies/Sphere/pusher enemy attack.fbx
  Assets/Resources/Models/Enemies/Sphere/pusher enemy attack.fbx.meta
  Assets/Resources/Models/Enemies/Sphere/pusher enemy idle.fbx
  Assets/Resources/Models/Enemies/Sphere/pusher enemy idle.fbx.meta
  Assets/Resources/Models/Enemies/Triangle/Model.fbx
  Assets/Resources/Models/Enemies/Triangle/Model.fbx.meta
  Assets/Resources/Models/Enemies/Triangle/killer enemy model.fbx
  Assets/Resources/Models/Enemies/Triangle/killer enemy model.fbx.meta
  Assets/Scripts/Level/Entities/AggressiveEntity.cs
  Assets/Scripts/Level/Entities/RandomPathAwareEntity.cs
  Assets/Scripts/Level/Entities/SphereEntity.cs
  Assets/Scripts/Level/Player/Behaviour/PlayerMovementBehaviour.cs
  ProjectSettings/ProjectSettings.asset
Labels: enhancement, Game dev

#98 Monetization added
  Assets/CoinsButton.cs
  Assets/CoinsButton.cs.meta
  Assets/CoinsVisor.cs
  Assets/CoinsVisor.cs.meta
  Assets/DeathScreen.cs
  Assets/FullScreenAd.cs
  Assets/MovesCounter.cs
  Assets/ReplayFromDeath.cs
  Assets/Resources/Interface/Coin.png
  Assets/Resources/Interface/Coin.png.meta
  Assets/Scenes/Level.unity
  Assets/Scenes/Menu.unity
  Assets/Scripts/Data/PlayerPersistentData.cs
  Assets/Scripts/Level/Player/Data/PlayerData.cs
Labels: bug, enhancement, Game dev

#101 Add drown death animation and fix waterlogged spawners.
  Assets/Resources/Levels/level_3_5.bytes
  Assets/Resources/Models/Player/animations/Drown.anim
  Assets/Resources/Models/Player/animations/Drown.anim.meta
  Assets/Resources/Models/Player/animations/PlayerAnimator.controller
  Assets/Resources/Models/Player/animations/character drown.fbx
  Assets/Resources/Models/Player/animations/character drown.fbx.meta
  Assets/Scripts/Level/Entities/SharkEntity.cs
  Assets/Scripts/Level/Entities/TriangleEntity.cs
  Assets/Scripts/Level/Generator/LevelGenerator.cs
  Assets/Scripts/Level/Player/Data/PlayerData.cs
  Assets/Scripts/Level/Player/PlayerDeathCause.cs
  Assets/Scripts/Level/Player/PlayerDeathCause.cs.meta
Labels: bug, enhancement, Game dev

#102 Improve the transition between the menu and the level scenes.
  Assets/PauseMenu.cs
  Assets/Scenes/Level.unity
  Assets/Scenes/Menu.unity
  Assets/Scripts/Level/Generator/LevelGenerator.cs
  Assets/Scripts/UI/Game/LevelCompletedScreen.cs
  Assets/Scripts/UI/Menu/LevelSelectionManager.cs
  Assets/Scripts/UI/MenuGO.cs
  Assets/Scripts/UI/MenuGO.cs.meta
  Assets/Sources/Level/Block.cs
  Assets/StarsDisplay.cs
Labels: enhancement, Game dev

#103 Start skin system.
  Assets/Resources/Models/Player/Dither.mat
  Assets/Resources/Models/Player/Outside.mat
  Assets/Resources/Skins.meta
  Assets/Resources/Skins/BlueSkin.prefab
  Assets/Resources/Skins/BlueSkin.prefab.meta
  Assets/Resources/Skins/GraySkin.prefab
  Assets/Resources/Skins/GraySkin.prefab.meta
  Assets/Resources/Skins/GreenSkin.prefab
  Assets/Resources/Skins/GreenSkin.prefab.meta
  Assets/Resources/Skins/PinkSkin.prefab
  Assets/Resources/Skins/PinkSkin.prefab.meta
  Assets/Resources/Skins/Player.prefab
  Assets/Resources/Skins/Player.prefab.meta
  Assets/Resources/Skins/PurpleSkin.prefab
  Assets/Resources/Skins/PurpleSkin.prefab.meta
  Assets/Resources/Skins/RedSkin.prefab
  Assets/Resources/Skins/RedSkin.prefab.meta
  Assets/Scenes/Level.unity
  Assets/Scenes/Menu.unity
  Assets/Scripts/Data/DataAccess.cs
  Assets/Scripts/Data/PersistentDataContainer.cs
  Assets/Scripts/Data/PlayerPersistentData.cs
  Assets/Scripts/Level/Generator/LevelGenerator.cs
  Assets/Scripts/Skins.meta
  Assets/Scripts/Skins/PlayerSkinColor.cs
  Assets/Scripts/Skins/PlayerSkinColor.cs.meta
  Assets/Scripts/UI/Game/LevelCompletedScreen.cs
  Assets/Scripts/UI/Menu/LevelSelectionManager.cs
  Assets/Shaders/PlayerDitherShader.shadergraph
  Assets/Sources/Identification/Identifier.cs
  Assets/Sources/Identification/Identifiers.cs
  Assets/Sources/Level/LevelCompletionData.cs
  Assets/Sources/Level/LevelToLoad.cs
  Assets/Sources/Level/Manager/LevelManager.cs
  Assets/Sources/LevelData.cs
  Assets/Sources/Registration/Registry.cs
  Assets/Sources/Skins.meta
  Assets/Sources/Skins/Skin.cs
  Assets/Sources/Skins/Skin.cs.meta
  Assets/Sources/Skins/SkinManager.cs
  Assets/Sources/Skins/SkinManager.cs.meta
Labels: enhancement, Game dev

#104 actualized comics
  Assets/Resources/Concept/new comics/1.png
  Assets/Resources/Concept/new comics/2.png
  Assets/Resources/Concept/new comics/3.png
  Assets/Resources/Concept/new comics/4.png
  Assets/Resources/Concept/new comics/4_1.png
  Assets/Resources/Concept/new comics/4_dialogos/4 1.png
  Assets/Resources/Concept/new comics/4_dialogos/4 2.png
  Assets/Resources/Concept/new comics/4_dialogos/4.png
  Assets/Resources/Concept/new comics/5.png
  Assets/Resources/Concept/new comics/5_dialogos/5_1.png
  Assets/Resources/Concept/new comics/5_dialogos/5_2.png
  Assets/Resources/Concept/new comics/6.png
Labels: enhancement, Art

#105 Introductory Cutscene
  Assets/Audio/Cutscene.meta
  Assets/Audio/Cutscene/introMusic.mp3
  Assets/Audio/Cutscene/introMusic.mp3.meta
  Assets/Audio/Cutscene/king.mp3
  Assets/Audio/Cutscene/king.mp3.meta
  Assets/Audio/Cutscene/panic.mp3
  Assets/Audio/Cutscene/panic.mp3.meta
  Assets/Audio/Cutscene/portal.mp3
  Assets/Audio/Cutscene/portal.mp3.meta
  Assets/Audio/Cutscene/scientist.mp3
  Assets/Audio/Cutscene/scientist.mp3.meta
  Assets/Cutscene.meta
  Assets/Cutscene/Cutscene Manager.controller
  Assets/Cutscene/Cutscene Manager.controller.meta
  Assets/Cutscene/Cutscene.anim
  Assets/Cutscene/Cutscene.anim.meta
  Assets/IntroManager.cs
  Assets/LoadMenu.cs
  Assets/LoadMenu.cs.meta
  Assets/Resources/Concept/comics/1.png
  Assets/Resources/Concept/comics/1.png.meta
  Assets/Resources/Concept/comics/2.png
  Assets/Resources/Concept/comics/2.png.meta
  Assets/Resources/Concept/comics/3.png
  Assets/Resources/Concept/comics/3.png.meta
  Assets/Resources/Concept/comics/4 6.png
  Assets/Resources/Concept/comics/4.png
  Assets/Resources/Concept/comics/4.png.meta
  Assets/Resources/Concept/comics/4_1.png
  Assets/Resources/Concept/comics/4_1.png.meta
  Assets/Resources/Concept/comics/4_dialogos/4 1.png
  Assets/Resources/Concept/comics/4_dialogos/4 1.png.meta
  Assets/Resources/Concept/comics/4_dialogos/4 2.png
  Assets/Resources/Concept/comics/4_dialogos/4 2.png.meta
  Assets/Resources/Concept/comics/4_dialogos/4 3.png
  Assets/Resources/Concept/comics/4_dialogos/4 4.png
  Assets/Resources/Concept/comics/4_dialogos/4 5.png
  Assets/Resources/Concept/comics/4_dialogos/4.png
  Assets/Resources/Concept/comics/4_dialogos/4.png.meta
  Assets/Resources/Concept/comics/5.png
  Assets/Resources/Concept/comics/5.png.meta
  Assets/Resources/Concept/comics/5_dialogos/5 1.png
  Assets/Resources/Concept/comics/5_dialogos/5.png
  Assets/Resources/Concept/comics/5_dialogos/5.png.meta
  Assets/Resources/Concept/comics/5_dialogos/5_1.png
  Assets/Resources/Concept/comics/5_dialogos/5_1.png.meta
  Assets/Resources/Concept/comics/5_dialogos/5_2.png
  Assets/Resources/Concept/comics/5_dialogos/5_2.png.meta
  Assets/Resources/Concept/comics/6.png
  Assets/Resources/Concept/comics/6.png.meta
  Assets/Scenes/Cutscene.unity
  Assets/Scenes/Cutscene.unity.meta
  ProjectSettings/EditorBuildSettings.asset
Labels: enhancement, Art, Game dev

#106 Menu properly working.
  Assets/Resources/Models/miniWorlds/LavaWorld/Old World/Materials/miniLava-5-world.png.meta
  Assets/Scenes/Menu.unity
  Assets/Scripts/Data/PlayerPersistentData.cs
  Assets/Scripts/UI/Menu/LevelSelectionManager.cs
Labels: enhancement, Game dev

#107 Refresh menu when player exits the level.
  Assets/PauseMenu.cs
  Assets/Scripts/UI/Game/LevelCompletedScreen.cs
  Assets/Scripts/UI/Menu/LevelSelectionManager.cs
Labels: bug, Game dev

#108 Add load screen when the level is being loaded.
  Assets/LoadinScreen.meta
  Assets/LoadingSceneAnim.anim
  Assets/LoadingSceneAnim.anim.meta
  Assets/LoadingSceneAnim.cs
  Assets/LoadingSceneAnim.cs.meta
  Assets/PauseMenu.cs
  Assets/Scenes/Menu.unity
  Assets/Scripts/UI/Game/LevelCompletedScreen.cs
  Assets/Scripts/UI/Menu/LevelSelectionManager.cs
  Assets/Scripts/UI/MenuGO.cs
  Assets/Text (TMP).controller
  Assets/Text (TMP).controller.meta
Labels: enhancement, Game dev

#109 Add Skip Scene Button
  Assets/Scenes/Cutscene.unity
  Assets/SkipScene.cs
  Assets/SkipScene.cs.meta
Labels: enhancement, Game dev

#110 Add: locked worlds interface
  Assets/Scenes/Level.unity
  Assets/Scenes/Menu.unity
  Assets/Scripts/UI/Menu/WorldSelection.cs
Labels: enhancement, Game dev

#112 Fix levels 1-2, 1-3 and 1-4 coins. Fix coins count.
  Assets/CoinsButton.cs
  Assets/Resources/Levels/level_1_2.bytes
  Assets/Resources/Levels/level_1_3.bytes
  Assets/Resources/Levels/level_1_4.bytes
  Assets/Scenes/Level.unity
  Assets/Scenes/Menu.unity
  Assets/Scripts/Data/PlayerPersistentData.cs
  ProjectSettings/ProjectSettings.asset
Labels: bug

#113 Add small script to save persistant data. Fix free coins button.
  Assets/Scenes/Level.unity
  Assets/Scripts/UI/PersistentDataSave.cs
  Assets/Scripts/UI/PersistentDataSave.cs.meta
Labels: enhancement, Game dev

#114 Add skin store and skin selector.
  Assets/BlockTypeDisplay.cs
  Assets/BlockTypeDisplay.cs.meta
  Assets/Prefabs/Button.prefab
  Assets/Prefabs/Button.prefab.meta
  Assets/Resources/Models/Player/Dither.mat
  Assets/Resources/SkinPictures.meta
  Assets/Resources/SkinPictures/block_dasher-skin_blue.png
  Assets/Resources/SkinPictures/block_dasher-skin_blue.png.meta
  Assets/Resources/SkinPictures/block_dasher-skin_default.png
  Assets/Resources/SkinPictures/block_dasher-skin_default.png.meta
  Assets/Resources/SkinPictures/block_dasher-skin_gray.png
  Assets/Resources/SkinPictures/block_dasher-skin_gray.png.meta
  Assets/Resources/SkinPictures/block_dasher-skin_green.png
  Assets/Resources/SkinPictures/block_dasher-skin_green.png.meta
  Assets/Resources/SkinPictures/block_dasher-skin_pink.png
  Assets/Resources/SkinPictures/block_dasher-skin_pink.png.meta
  Assets/Resources/SkinPictures/block_dasher-skin_purple.png
  Assets/Resources/SkinPictures/block_dasher-skin_purple.png.meta
  Assets/Resources/SkinPictures/block_dasher-skin_red.png
  Assets/Resources/SkinPictures/block_dasher-skin_red.png.meta
  Assets/Resources/Skins/BlueSkin.prefab
  Assets/Resources/Skins/GraySkin.prefab
  Assets/Resources/Skins/GreenSkin.prefab
  Assets/Resources/Skins/PinkSkin.prefab
  Assets/Resources/Skins/PurpleSkin.prefab
  Assets/Resources/Skins/RedSkin.prefab
  Assets/Scenes/Menu.unity
  Assets/Scripts/Data/PlayerPersistentData.cs
  Assets/SkinCoinsButton.cs
  Assets/SkinCoinsButton.cs.meta
  Assets/SkinStorageScrollView.cs
  Assets/SkinStorageScrollView.cs.meta
  Assets/SkinTypeDisplay.cs
  Assets/SkinTypeDisplay.cs.meta
Labels: enhancement, Game dev
