Repository Slow-Heat-Index/BlockDasher, pull requests merged in 2021-12, with the labels that each got.

#137 Fix a bug that allowed the player to restart the level after they dies.
  Assets/PauseMenu.cs
  Assets/Scripts/Level/Player/Data/PlayerData.cs
Labels: bug

#138 Add a delay to the camera rotation.
  Assets/Scripts/Level/Cameras/Behaviour/LevelCameraBehaviour.cs
Labels: bug

#139 Status icons are now hidden on reset.
  Assets/Scripts/Level/Player/Data/PlayerData.cs
Labels: bug

#140 Fix dash counter reset on menu pause.
  Assets/MovesCounter.cs
  Assets/Resources/Models/Blocks/BeachSand/WhiteMaterial.mat
  Assets/Resources/Models/Blocks/End/DefaultMaterial.mat
  Assets/Scripts/Level/Player/Data/PlayerData.cs
Labels: bug, Game dev

#142 Tutorial Tooltip Display
  Assets/Resources/Interface/Tutorial.meta
  Assets/Resources/Interface/Tutorial/ArrowsTut.png.meta
  Assets/Resources/Interface/Tutorial/DashTutorial.png.meta
  Assets/Resources/Interface/Tutorial/ManoTut.png.meta
  Assets/Resources/Interface/Tutorial/MovilTut.png.meta
  Assets/Resources/Interface/Tutorial/WASDTut.png.meta
  Assets/Resources/Interface/Tutorial/WASDwithArrowsTut.png.meta
  Assets/Scenes/Level.unity
  Assets/Scripts/Level/Player/Behaviour/PlayerMovementBehaviour.cs
  Assets/Scripts/Level/Player/Data/PlayerData.cs
  Assets/TutorialDisplay.cs
  Assets/TutorialDisplay.cs.meta
  Assets/UIAnimations.meta
  Assets/UIAnimations/MobileToolTipAnimation.anim
  Assets/UIAnimations/MobileToolTipAnimation.anim.meta
  Assets/UIAnimations/Phone.controller
  Assets/UIAnimations/Phone.controller.meta
Labels: enhancement

#143 Fix Ads Button
  Assets/RemoveAds.cs
  Assets/RemoveAds.cs.meta
  Assets/Scenes/Menu.unity
  Assets/Scripts/Data/PlayerPersistentData.cs
  Assets/Scripts/ReplayFromDeath.cs
Labels: bug, Game dev

#144 Restart button
  Assets/Inputs/Inputs.cs
  Assets/Inputs/Inputs.inputactions
  Assets/Scenes/Level.unity
  Assets/Scenes/Menu.unity
  Assets/Scripts/Level/Player/Controller/PlayerMovementController.cs
  Assets/Scripts/Level/Player/Data/PlayerData.cs
Labels: enhancement, Game dev

#147 Fix camera position when colliding with blocks.
  Assets/Resources/Models/Blocks/BeachGrass/DirtMaterial.mat
  Assets/Scenes/Level.unity
  Assets/Scripts/Level/Cameras/Behaviour/LevelCameraBehaviour.cs
  Assets/Scripts/TutorialDisplay.cs
  Assets/Scripts/Util/VectorUtils.cs
  Assets/Scripts/Util/VectorUtils.cs.meta
  Assets/Sources/Level/Raycast/BlockRaycaster.cs
Labels: bug, Game dev
